spring:
  application:
    name: ai-message-creator
  # MySQL 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_passage_creator
    username: root
    password: kong0305
mybatis-flex:
  configuration:
    map-underscore-to-camel-case: false
  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
  # Redis 配置
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password:
server:
  port: 8123
  servlet:
    session:
      cookie:
        max-age: 2592000
    context-path: /api
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.jaychou.aipassagecreator.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
