spring:
  profiles:
    active: local
  application:
    name: ai-message-creator
  session:
    store-type: redis
    timeout: 2592000

mybatis-flex:
  configuration:
    map-underscore-to-camel-case: false

server:
  servlet:
    session:
      cookie:
        max-age: 2592000
    context-path: /api

# 接口文档
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.jaychou.aipassagecreator.controller

knife4j:
  enable: true
  setting:
    language: zh_cn


