spring:
  # MySQL 本地库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_passage_creator
    username: root
    password: kong0305
  # 本地Redis
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password:
  # 本地AI密钥
  ai:
    dashscope:
      api-key: sk-1f3b39691b674d60ba5463ec1f705a02

# 本地端口
server:
  port: 8123